name: Release

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags like v1.0.0, v1.0.1, etc.

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-libs
          path: build/libs/
      - name: create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/libs/drandomspawn-*.jar
          generate_release_notes: true
